--- # FETCH MODULE EXAMPLE

- hosts: slave

  user: user

  become: yes

  connection: ssh

  tasks:

    - name: Copy remote hosts file to control server

      fetch: src=/etc/hostname dest=/home/user/prefix-{{ ansible_hostname }} flat=yes
