--- 

- hosts: slave

  user: user

  become: yes

  connection: ssh

  tasks:

  - name: Install Web Server

    apt: name=apache2 state=present

  - name: Start the Web Server

    service: name=apache2 state=started

  - name: Enable HTTPD After Reboot

    service: name=apache2 enabled=yes
