---
- hosts: slave
  become: yes
  gather_facts: no
  tasks:
    - name: Add the user called tstapache to the apache web client
      user: name=tst comment="tst user" shell=/bin/bash groups=user append=yes
