--- 
- hosts: slave
  become: yes
  gather_facts: no
  tasks:

    - name: Installing Apache Tomcat
      action: apt name=tomcat8 state=present

    - name: Waiting for Port 8080 to Listen
      wait_for:
        port: 8080
        state: started

    - name: Verifying Lynx Installation
      action: apt name=lynx state=present
